### ISSUE TITLE
Can you explain how your read model works?

### ISSUE THREAD

**Issue by zeyser** [adelf/freelance-example#5]
You have in Read Controllers call such as `Freelancer::findOrFail($id);` What is happening next? I see that Model have __callStatic method, that will call _findOrFail_ but where declaration of that method?

**Comment by adelf** [comment]
Hi, @zeyser .
It's Laravel's Eloquent package. Inside __callStatic it creates a Builder object and findOrFail method is here - https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Builder.php#L359

**Comment by zeyser** [comment]
@adelf Thank you for quick answer and explanation!
